export const MODULES = 'modules'
export const NODE_ENV = process.env.NODE_ENV || 'development'
export const DEFAULTE_ROUTE = process.env.DEFAULTE_ROUTE || ''
export const API_SERVER = process.env.API_SERVER || ''
export const CONFIG_TYPE = process.env.CONFIG_TYPE || 'rc'
